### ISSUE TITLE
Stack trace of error on GET /vehicles

### ISSUE THREAD

**Issue by RobBowden** [headforwards/tesla-simulator-server#6]
Steps to reproduce:

curl X POST --data "email=test@123.com&password=1234" http://tesla.headforwards.com/oauth/tokens

Then use the reported acces_token in:

curl --header "Authorization: Bearer {6f67efd2-9356-4f9a-af53-f6e4baaf5e8b}" http://tesla.headforwards.com/api/1/vehicles

Spits out:

**Comment by benflodge** [comment]
This issue should be fixed by #7 
There was an issue getting the user id from the vehicle.

**Comment by glenpike** [comment]
Fixed by #7
